version: '2.1'

services:
  muximux:
    image: linuxserver/muximux:latest
    container_name: muximux
    restart: always
    network_mode: "host"  
    ports:
      - 8888:80
    volumes:
      - /home/$USER/docker_files/muximux:/config
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
      
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: "MQTT"
    restart: always
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /home/$USER/docker_files/mqtt/data:/mosquitto/data
      - /home/$USER/docker_files/mqtt/config:/mosquitto/config
      - /home/$USER/docker_files/mqtt/log:/mosquitto/log
    network_mode: "host"
    environment:
      - TZ=America/New_York

  grafana:
    image: grafana/grafana:latest
    container_name: "grafana"
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      - TZ=America/New_York
      - PGID=1000
      - PUID=1000
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - /home/$USER/docker_files/grafana:/var/lib/grafana
    network_mode: host

  influxdb:
    image: influxdb:latest
    container_name: "influxdb"
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
      interval: 30s
      timeout: 1s
      retries: 24
    network_mode: host
    environment:
      - TZ=America/New_York
    ports:
      - 8083:8083
      - 8086:8086
    restart: on-failure
    volumes:
      - /home/$USER/docker_files/influxdb:/var/lib/influxdb

  home-assistant:
    #image: homeassistant/home-assistant:0.64.3
    image: homeassistant/home-assistant:latest
    container_name: "hass"
    restart: always
    depends_on:
      influxdb:
        condition: service_healthy
      mqtt:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "https://REDACTED"]
      interval: 30s
      timeout: 10s
      retries: 6
    ports:
      - 8123:8123
    volumes:
      - /home/$USER/docker_files/homeassistant/config:/config
    network_mode: "host"
    environment:
      - TZ=America/New_York

  mqtt-bridge:
    container_name: mqtt-bridge
    image: stjohnjohnson/smartthings-mqtt-bridge
    ports:
      - 8080:8080
    volumes:
      - /home/$USER/docker_files/mqtt-bridge:/config
    restart: on-failure
    depends_on:
      home-assistant:
        condition: service_healthy

  node-red:
    container_name: node-red
    image: nodered/node-red-docker
    ports:
      - 1880:1880
    volumes:
      - /home/$USER/docker_files/node-red:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: "no" # because the exit code(s) are wrong
    depends_on:
      mqtt:
        condition: service_started
      mqtt-bridge:
        condition: service_started
      home-assistant:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:1880"]
      interval: 30s
      timeout: 10s
      retries: 5

  dockermon:
    container_name: dockermon
    image: philhawthorne/ha-dockermon
    ports:
      - 8126:8126
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/$USER/docker_files/dockermon:/config
    restart: on-failure

  organizr:
    container_name: organizr
    image: lsioarmhf/organizr
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/$USER/docker_files/organizr:/config:rw
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - PGID=1000
      - PUID=1000
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # minecraft:
    # #image: itzg/minecraft-server
    # image: ashdev/docker-spigot:1.12.2
    # container_name: "MC"
    # ports:
      # - "25565:25565"
    # volumes:
      # #- ./minecraft/data:/data
      # - ./minecraft/data:/minecraft
    # tty: true
    # stdin_open: true
    # restart: always
    # network_mode: "host"
    # environment:
      # EULA: "TRUE"
      # #TYPE: "FORGE"
      # DIFFICULTY: "normal"
      # OPS: "REDACTED"
      # #ICON: "https://pbs.twimg.com/profile_images/938049421459288064/1gdDDKnH_400x400.jpg"
      # ENABLE_COMMAND_BLOCK: "true"
      # ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      # GENERATE_STRUCTURES: "true"
